# Generated by Django 5.2.4 on 2026-06-03 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mantenedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudRMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('rut_cliente', models.CharField(max_length=20)),
                ('contacto', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=255)),
                ('tipo_documento', models.CharField(blank=True, max_length=50)),
                ('numero_documento', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_revision', 'En Revisión'), ('diagnosticado', 'Diagnosticado'), ('cerrado', 'Cerrado')], default='abierto', max_length=20)),
                ('en_garantia', models.BooleanField(default=False)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_equipo', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion_falla', models.TextField(blank=True, null=True)),
                ('sellos_intactos', models.BooleanField(default=False)),
                ('accesorios_recibidos', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenedor.localidad')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rmas', to='mantenedor.cliente')),
                ('fabricante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenedor.fabricante')),
            ],
        ),
        migrations.CreateModel(
            name='RMAImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='rma/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('rma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='gestor_rma.solicitudrma')),
            ],
        ),
        migrations.CreateModel(
            name='ResolucionRMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingeniero_responsable', models.CharField(max_length=200)),
                ('condicion_fisica', models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('dañado', 'Dañado')], max_length=20)),
                ('sellos_intactos', models.BooleanField(default=False)),
                ('accesorios_recibidos', models.TextField(blank=True)),
                ('descripcion_falla', models.TextField(blank=True)),
                ('diagnostico', models.CharField(max_length=200)),
                ('causa_raiz', models.CharField(blank=True, max_length=255)),
                ('aplica_garantia', models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazada', 'Rechazada'), ('rma_fabrica', 'RMA a Fábrica'), ('no_aplica', 'No Aplica')], max_length=200)),
                ('motivo_no_garantia', models.TextField(blank=True)),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True)),
                ('observaciones_cliente', models.TextField(blank=True)),
                ('rma_imagen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestor_rma.rmaimagen')),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestor_rma.solicitudrma')),
            ],
        ),
    ]
