# Generated by Django 5.2.4 on 2026-06-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_rma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudrma',
            name='nombre_cliente',
        ),
        migrations.AlterField(
            model_name='solicitudrma',
            name='accesorios_recibidos',
            field=models.CharField(choices=[('completo', 'Completo'), ('incompleto', 'Incompleto'), ('na', 'N/A')], max_length=10),
        ),
        migrations.AlterField(
            model_name='solicitudrma',
            name='sellos_intactos',
            field=models.CharField(choices=[('cerrado', 'Cerrado'), ('abierto', 'Abierto'), ('na', 'N/A')], max_length=10),
        ),
        migrations.AlterField(
            model_name='solicitudrma',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('factura', 'Factura'), ('nota_venta', 'Nota de Venta'), ('otro', 'Otro')], max_length=50),
        ),
    ]
