# Generated by Django 5.2.4 on 2026-06-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_rma', '0002_remove_solicitudrma_nombre_cliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resolucionrma',
            old_name='observaciones_cliente',
            new_name='observaciones',
        ),
        migrations.AlterField(
            model_name='resolucionrma',
            name='accesorios_recibidos',
            field=models.CharField(choices=[('completo', 'Completo'), ('incompleto', 'Incompleto'), ('na', 'N/A')], max_length=10),
        ),
        migrations.AlterField(
            model_name='resolucionrma',
            name='sellos_intactos',
            field=models.CharField(choices=[('cerrado', 'Cerrado'), ('abierto', 'Abierto'), ('na', 'N/A')], max_length=10),
        ),
    ]
