# Generated by Django 5.2.4 on 2026-06-08 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tickets', '0004_ticket_ciudad'),
        ('gestor_rma', '0003_rename_observaciones_cliente_resolucionrma_observaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudrma',
            name='numero_rma',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='solicitudrma',
            name='ticket_origen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rma', to='gestion_tickets.ticket'),
        ),
        migrations.AlterField(
            model_name='resolucionrma',
            name='solicitud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolucion', to='gestor_rma.solicitudrma'),
        ),
    ]
