# Generated by Django 5.2.4 on 2026-06-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_rma', '0004_solicitudrma_numero_rma_solicitudrma_ticket_origen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudrma',
            name='fecha_cierre',
        ),
        migrations.AddField(
            model_name='resolucionrma',
            name='numero_resolucion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
