# Generated by Django 5.2.4 on 2026-06-20 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_rma', '0005_remove_solicitudrma_fecha_cierre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rmaimagen',
            name='fecha_subida',
        ),
        migrations.AlterField(
            model_name='rmaimagen',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rmaimagen',
            name='rma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_rma.solicitudrma'),
        ),
    ]
