# Generated by Django 5.2.4 on 2026-06-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_rma', '0006_remove_rmaimagen_fecha_subida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudrma',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
