# Generated by Django 5.2.4 on 2026-06-22 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CelularTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('imei1', models.CharField(max_length=50)),
                ('imei2', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_sim1', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_sim2', models.CharField(blank=True, max_length=20, null=True)),
                ('version_os', models.CharField(max_length=50)),
                ('clave_bloqueo', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(default='operativo', max_length=50)),
                ('responsable_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celulares_asignados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EquipoTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_equipo', models.CharField(choices=[('notebook', 'Notebook'), ('macbook', 'MacBook'), ('workstation', 'Estación de trabajo'), ('tablet', 'Tablet'), ('lector_codigo', 'Lector de código'), ('monitor', 'Monitor'), ('proyector', 'Proyector')], max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('cpu', models.CharField(max_length=100)),
                ('ram_gb', models.IntegerField()),
                ('tipo_disco', models.CharField(choices=[('HDD', 'HDD'), ('SSD', 'SSD'), ('M2', 'M.2')], max_length=20)),
                ('capacidad_disco_gb', models.IntegerField()),
                ('sistema_operativo', models.CharField(max_length=100)),
                ('licencia_windows_key', models.CharField(blank=True, max_length=200, null=True)),
                ('accesorios', models.JSONField(default=dict)),
                ('estado_equipo', models.CharField(default='operativo', max_length=50)),
                ('responsable_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LicenciaTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_licencia', models.CharField(max_length=50)),
                ('producto', models.CharField(max_length=100)),
                ('clave', models.CharField(max_length=200)),
                ('correo_asociado', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('fecha_expiracion', models.DateField(blank=True, null=True)),
                ('responsable_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licencias_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('motivo_termino', models.CharField(blank=True, choices=[('despido', 'Despido'), ('renuncia', 'Renuncia'), ('falla', 'Falla'), ('renovacion', 'Renovación'), ('otro', 'Otro')], max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('celular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario_ti.celularti')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario_ti.equipoti')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('licencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario_ti.licenciati')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('archivo_pdf', models.FileField(upload_to='documentos_entrega/')),
                ('celulares', models.ManyToManyField(blank=True, to='inventario_ti.celularti')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('equipos', models.ManyToManyField(blank=True, to='inventario_ti.equipoti')),
                ('licencias', models.ManyToManyField(blank=True, to='inventario_ti.licenciati')),
            ],
        ),
    ]
