# Generated by Django 5.2.4 on 2026-06-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_ti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipoti',
            name='accesorios',
            field=models.CharField(max_length=250),
        ),
    ]
