# Generated by Django 5.2.4 on 2026-06-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_ti', '0002_alter_equipoti_accesorios'),
    ]

    operations = [
        migrations.AddField(
            model_name='celularti',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
