# Generated by Django 5.2.4 on 2026-06-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='ciudad',
            field=models.CharField(choices=[('Región de Arica y Parinacota', [('ARICA', 'Arica')]), ('Región de Tarapacá', [('IQUIQUE', 'Iquique'), ('ALTO_HOSPICIO', 'Alto Hospicio'), ('POZO_ALMONTE', 'Pozo Almonte')]), ('Región de Antofagasta', [('ANTOFAGASTA', 'Antofagasta'), ('CALAMA', 'Calama'), ('TOCOPILLA', 'Tocopilla'), ('MEJILLONES', 'Mejillones'), ('TALTAL', 'Taltal')]), ('Región de Atacama', [('COPIAPO', 'Copiapó'), ('VALLENAR', 'Vallenar'), ('CHANARAL', 'Chañaral'), ('CALDERA', 'Caldera')]), ('Región de Coquimbo', [('LA_SERENA', 'La Serena'), ('COQUIMBO', 'Coquimbo'), ('OVALLE', 'Ovalle'), ('ILLAPEL', 'Illapel'), ('VICUNA', 'Vicuña'), ('SALAMANCA', 'Salamanca')]), ('Región de Valparaíso', [('VALPARAISO', 'Valparaíso'), ('VINA_DEL_MAR', 'Viña del Mar'), ('QUILPUE', 'Quilpué'), ('VILLA_ALEMANA', 'Villa Alemana'), ('SAN_ANTONIO', 'San Antonio'), ('QUILLOTA', 'Quillota'), ('SAN_FELIPE', 'San Felipe'), ('LOS_ANDES', 'Los Andes'), ('LA_CALERA', 'La Calera'), ('LIMACHE', 'Limache')]), ('Región Metropolitana de Santiago', [('SANTIAGO', 'Santiago'), ('PUENTE_ALTO', 'Puente Alto'), ('SAN_BERNARDO', 'San Bernardo'), ('MELIPILLA', 'Melipilla'), ('TALAGANTE', 'Talagante'), ('BUIN', 'Buin'), ('PENAFLOR', 'Peñaflor'), ('COLINA', 'Colina'), ('CURACAVI', 'Curacaví')]), ("Región del Libertador General Bernardo O'Higgins", [('RANCAGUA', 'Rancagua'), ('SAN_FERNANDO', 'San Fernando'), ('RENGO', 'Rengo'), ('PICHILEMU', 'Pichilemu'), ('SAN_VICENTE', 'San Vicente de Tagua Tagua')]), ('Región del Maule', [('TALCA', 'Talca'), ('CURICO', 'Curicó'), ('LINARES', 'Linares'), ('CAUQUENES', 'Cauquenes'), ('CONSTITUCION', 'Constitución'), ('PARRAL', 'Parral'), ('SAN_JAVIER', 'San Javier')]), ('Región de Ñuble', [('CHILLAN', 'Chillán'), ('SAN_CARLOS', 'San Carlos'), ('BULNES', 'Bulnes'), ('COELEMU', 'Coelemu')]), ('Región del Biobío', [('CONCEPCION', 'Concepción'), ('TALCAHUANO', 'Talcahuano'), ('SAN_PEDRO_DE_LA_PAZ', 'San Pedro de la Paz'), ('CHIGUAYANTE', 'Chiguayante'), ('CORONEL', 'Coronel'), ('LOTA', 'Lota'), ('LOS_ANGELES', 'Los Ángeles'), ('PENCO', 'Penco'), ('TOME', 'Tomé'), ('CURANILAHUE', 'Curanilahue')]), ('Región de La Araucanía', [('TEMUCO', 'Temuco'), ('ANGOL', 'Angol'), ('VILLARRICA', 'Villarrica'), ('PUCON', 'Pucón'), ('LAUTARO', 'Lautaro'), ('NUEVA_IMPERIAL', 'Nueva Imperial'), ('VICTORIA', 'Victoria')]), ('Región de Los Ríos', [('VALDIVIA', 'Valdivia'), ('LA_UNION', 'La Unión'), ('RIO_BUENO', 'Río Bueno'), ('PANGUIPULLI', 'Panguipulli')]), ('Región de Los Lagos', [('PUERTO_MONTT', 'Puerto Montt'), ('OSORNO', 'Osorno'), ('PUERTO_VARAS', 'Puerto Varas'), ('CASTRO', 'Castro'), ('ANCUD', 'Ancud'), ('QUELLON', 'Quellón'), ('CALBUCO', 'Calbuco')]), ('Región de Aysén del General Carlos Ibáñez del Campo', [('COYHAIQUE', 'Coyhaique'), ('PUERTO_AYSEN', 'Puerto Aysén'), ('CHILE_CHICO', 'Chile Chico')]), ('Región de Magallanes y de la Antártica Chilena', [('PUNTA_ARENAS', 'Punta Arenas'), ('PUERTO_NATALES', 'Puerto Natales'), ('PORVENIR', 'Porvenir')])], max_length=100),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='país',
            field=models.CharField(default='Chile', max_length=100),
        ),
    ]
