# Generated by Django 5.2.4 on 2025-09-14 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_tickets', '0005_ticket_fecha_cierre_alter_ticket_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SLAFabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(help_text='Ej: reemplazo, reparación, diagnóstico', max_length=100)),
                ('horas_respuesta', models.PositiveIntegerField()),
                ('horas_resolucion', models.PositiveIntegerField()),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_tickets.fabricante')),
            ],
        ),
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criticidad', models.CharField(choices=[('critico', 'Crítico'), ('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo')], max_length=10, unique=True)),
                ('horas_respuesta', models.PositiveIntegerField(help_text='Horas hábiles para responder')),
                ('horas_resolucion', models.PositiveIntegerField(help_text='Horas hábiles para resolver')),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.canalatencion')),
            ],
            options={
                'unique_together': {('criticidad', 'canal')},
            },
        ),
    ]
