# Generated by Django 5.2.4 on 2026-06-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanalAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets_fabricante', models.IntegerField(default=0, help_text='Número de tickets por Fabricante')),
                ('tickets_integrador', models.IntegerField(default=0, help_text='Número de tickets por Integrador')),
                ('tickets_tiempo_respuesta', models.IntegerField(default=0, help_text='Tiempo de respuesta en horas')),
                ('tickets_tiempo_resolucion', models.IntegerField(default=0, help_text='Tiempo de resolución en horas')),
                ('tickets_cumplimiento', models.FloatField(default=0.0, help_text='% de cumplimiento del SLA')),
                ('tickets_no_cumplimiento', models.FloatField(default=0.0, help_text='% de incumplimiento del SLA')),
                ('tickets_en_garantia', models.IntegerField(default=0, help_text='Número de tickets en garantía')),
                ('tickets_fuera_garantia', models.IntegerField(default=0, help_text='Número de tickets fuera de garantía')),
            ],
        ),
    ]
