# Generated by Django 5.2.4 on 2025-09-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sla',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sla',
            name='tickets_cumplimiento',
            field=models.FloatField(default=0.0, help_text='% de cumplimiento del SLA'),
        ),
        migrations.AddField(
            model_name='sla',
            name='tickets_en_garantia',
            field=models.IntegerField(default=0, help_text='Número de tickets en garantía'),
        ),
        migrations.AddField(
            model_name='sla',
            name='tickets_fabricante',
            field=models.IntegerField(default=0, help_text='Número de tickets por Fabricante'),
        ),
        migrations.AddField(
            model_name='sla',
            name='tickets_fuera_garantia',
            field=models.IntegerField(default=0, help_text='Número de tickets fuera de garantía'),
        ),
        migrations.AddField(
            model_name='sla',
            name='tickets_integrador',
            field=models.IntegerField(default=0, help_text='Número de tickets por Integrador'),
        ),
        migrations.AddField(
            model_name='sla',
            name='tickets_no_cumplimiento',
            field=models.FloatField(default=0.0, help_text='% de incumplimiento del SLA'),
        ),
        migrations.AddField(
            model_name='sla',
            name='tickets_tiempo_resolucion',
            field=models.IntegerField(default=0, help_text='Tiempo de resolución en horas'),
        ),
        migrations.AddField(
            model_name='sla',
            name='tickets_tiempo_respuesta',
            field=models.IntegerField(default=0, help_text='Tiempo de respuesta en horas'),
        ),
        migrations.DeleteModel(
            name='SLAFabricante',
        ),
        migrations.RemoveField(
            model_name='sla',
            name='canal',
        ),
        migrations.RemoveField(
            model_name='sla',
            name='criticidad',
        ),
        migrations.RemoveField(
            model_name='sla',
            name='horas_resolucion',
        ),
        migrations.RemoveField(
            model_name='sla',
            name='horas_respuesta',
        ),
    ]
