# Generated by Django 5.2.4 on 2026-06-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='area',
            field=models.CharField(choices=[('soporte', 'Soporte'), ('comercial', 'Comercial'), ('administracion', 'Administración'), ('logistica', 'Logística'), ('ti', 'TI'), ('digital', 'Digital')], default='soporte', max_length=30),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('completada', 'Completada'), ('atrasada', 'Atrasada')], default='Pendiente', max_length=20),
        ),
    ]
