# Generated by Django 5.2.4 on 2026-06-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_tareas', '0002_tarea_area_alter_tarea_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='area',
            field=models.CharField(choices=[('soporte', 'Soporte'), ('comercial', 'Comercial'), ('operaciones', 'Operaciones'), ('administracion', 'Administración'), ('logistica', 'Logística'), ('ti', 'TI'), ('almmadigital', 'AlmmaDigital')], default='soporte', max_length=30),
        ),
    ]
