# Generated by Django 5.2.4 on 2025-08-12 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario_soporte',
            options={'verbose_name': 'Usuario de Soporte', 'verbose_name_plural': 'Usuarios de Soporte'},
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='tipo_usuario',
        ),
        migrations.RemoveField(
            model_name='usuario_soporte',
            name='correo',
        ),
        migrations.AddField(
            model_name='perfil',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
