# Generated by Django 5.2.4 on 2026-05-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LlaveLicencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('cliente', models.CharField(max_length=200)),
                ('contacto', models.CharField(max_length=200)),
                ('tipo_llave', models.CharField(choices=[('WIBU', 'WIBU'), ('ESD', 'ESD')], max_length=10)),
                ('numero_serie', models.CharField(max_length=100)),
                ('fecha_vencimiento', models.DateField()),
                ('historial_pagos', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
