# Generated by Django 5.2.4 on 2026-05-17 01:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_llaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='llavelicencia',
            name='fecha_registro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
