# Generated by Django 5.2.4 on 2026-05-17 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_llaves', '0002_llavelicencia_fecha_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llavelicencia',
            name='historial_pagos',
        ),
        migrations.AlterField(
            model_name='llavelicencia',
            name='numero_serie',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='HistorialLicencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento_nueva', models.DateField()),
                ('tipo_documento', models.CharField(choices=[('FACTURA', 'Factura'), ('BOLETA', 'Boleta'), ('OC', 'Orden de Compra'), ('OTRO', 'Otro')], max_length=20)),
                ('numero_documento', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('llave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='gestion_llaves.llavelicencia')),
            ],
        ),
    ]
