# Generated by Django 5.2.4 on 2026-06-03 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mantenedor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('rut_cliente', models.CharField(max_length=20)),
                ('contacto', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_documento', models.CharField(choices=[('factura', 'Factura'), ('nota_venta', 'Nota de Venta'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('numero_documento', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('pendiente', 'Pendiente'), ('cerrado', 'Cerrado')], default='abierto', max_length=20)),
                ('en_garantia', models.BooleanField(default=False)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_equipo', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion_falla', models.TextField(blank=True, null=True)),
                ('sellos_intactos', models.CharField(choices=[('cerrado', 'Cerrado'), ('abierto', 'Abierto'), ('na', 'N/A')], max_length=10)),
                ('accesorios_recibidos', models.CharField(choices=[('completo', 'Completo'), ('incompleto', 'Incompleto'), ('na', 'N/A')], max_length=10)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenedor.localidad')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='mantenedor.cliente')),
                ('fabricante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenedor.fabricante')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('es_respuesta', models.BooleanField(default=True, verbose_name='¿Es una respuesta?')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='gestion_tickets.ticket')),
            ],
            options={
                'ordering': ['fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='TicketImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='tickets/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='gestion_tickets.ticket')),
            ],
        ),
    ]
