# Generated by Django 5.2.4 on 2026-06-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='nombre_cliente',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tipo_documento',
            field=models.CharField(choices=[('factura', 'Factura'), ('nota_venta', 'Nota de Venta'), ('otro', 'Otro')], default='factura', max_length=20),
        ),
    ]
