# Generated by Django 5.2.4 on 2026-06-04 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tickets', '0002_remove_ticket_nombre_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ciudad',
        ),
    ]
