# Generated by Django 5.2.4 on 2025-08-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tickets', '0002_alter_ticket_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fecha_creacion',
            field=models.DateField(auto_created=True),
        ),
    ]
