# Generated by Django 5.2.4 on 2026-06-04 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tickets', '0003_remove_ticket_ciudad'),
        ('mantenedor', '0003_alter_localidad_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenedor.localidad'),
        ),
    ]
