# Generated by Django 5.2.4 on 2025-09-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tickets', '0004_alter_ticket_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro'),
        ),
    ]
