# Generated by Django 5.2.4 on 2025-09-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tickets', '0005_ticket_fecha_cierre_alter_ticket_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tipo_servicio',
            field=models.CharField(choices=[('reparación', 'Reparación'), ('pruebas', 'Pruebas'), ('garantía', 'Garantía'), ('armado', 'Armado'), ('diagnóstico', 'Diagnóstico'), ('otro', 'Otro')], default='diagnostico', max_length=30, verbose_name='Tipo de Servicio'),
        ),
    ]
